name : Postman Collection workflow

on:
  push:
    branches: [main]
  workflow_dispatch: 
  schedule:
    - cron: '30 02 * * *'
    - cron: '30 13 * * *'
    - cron : '00 06 * * 1-5'

jobs:
  Run-postman-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v6.0.2

      - name: Install NodeJs and npm
        uses: actions/setup-node@v6.2.0
        with: 
          node-version: '22'

      - name: Install newman and htmlextra reporter globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the postman collection with newman
        run: | 
             newman run InWarranty_flow_Collection.postman_collection.json \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra

      - name: Newman html report
        if: always()
        uses: actions/upload-artifact@v6.0.0
        with: 
          name: Newman html report
          path: newman/*.html
        


             
            
          
          
      
        

      
